#==============================O==============================#
# I---------------------------------------------------------I #
# |          Pet Master 1.2 configuration - Readme          | #
# 1---------------------------------------------------------1 #
#==============================o==============================#

# Remember: nothing is displayed if you are the owner of the pet!
# Visit the GitHub for some additional documentation: github.com/PyvesB/PetMaster

#=============================O=O=============================#
# II-------------------------------------------------------II #
# |                    General  settings                    | #
# 2---------------------------------------------------------2 #
#=============================o=o=============================#
  
# Enable or disable chat messages when right-clicking on a pet.
chatMessage: true

# Enable or disable hologram messages when right-clicking on a pet.
hologramMessage: true

# Duration of the hologram, in server ticks (20 ticks = 1 second).
hologramDuration: 50

# Check for update on plugin launch and notify when an OP joins the game.
CheckForUpdate: true

# Name of the language file.
LanguageFileName: 'lang.yml'