name: PetMaster
main: com.hm.petmaster.PetMaster
version: 1.1
author: DarkPyves
softdepend: [HolographicDisplays]
load: POSTWORLD
description: Whose pet is this? A simple plugin to change or display the owner of a pet via a hologram or a chat message.
website: https://github.com/PyvesB/PetMaster
commands:
  petm:
    description: Main Pet Master command, use it to list sub-commands. 
    aliases: [petmaster]  
    usage: /<command>
permissions:
  petmaster.use:
    description: Allows to use the plugin.
    default: true
  petmaster.setowner:
    description: Allows players to change the ownership of their own pets.
    default: true
  petmaster.admin:
    description: Allows to enable/disable/reload the plugin, or bypass ownership setting.
    default: false
  petmaster.*:
    description: Star notation of permissions, includes all of them.
    default: op
    children:
      petmaster.use: true
      petmaster.admin: true
      petmaster.setowner: true
    
